name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/ibot
            # git pull
            export MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}
            export MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
            export TOKEN=${{ secrets.TOKEN }}
            export DB_NAME=${{ secrets.DB_NAME }}
            pkill -f "python bot.py"
            . venv/bin/activate
            python bot.py > bot.log 2>&1
